### PR TITLE
Fix compiling on macOS Sierra/clang

### PR DESCRIPTION
**Pull request by wendigo**
Related to https://github.com/golang/go/issues/17356

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm confused why this would be needed since I just shipped a Sierra bottle without issue:

https://github.com/Homebrew/homebrew-core/pull/6184
https://github.com/Homebrew/homebrew-core/commit/ad1bfc834732351c4864e50d8a2e6db21e5191c1
https://github.com/Homebrew/homebrew-core/commit/e574d434c5742e52f5e2794fc53e905fe59b05bc

What am I not understanding? Was an alternative fix merged?

**Comment by svent** [comment]
This PR is not needed anymore as I completely removed the old C code.
Please see the comment on #81 for details.

@ilovezfs Thanks for updating sift on Homebrew!

**Comment by ilovezfs** [comment]
@svent you're welcome. I knew there must be an explanation!

**Comment by wendigo** [comment]
@ilovezfs as @svent explained - this failed to compile on old version :)

**Pull request closed without merging**
