### PR TITLE
use klauspost's parallel gzip

### PR DESCRIPTION
**Pull request by mnikhil-git**
instead of stdlib gzip for parallel read

### CODE REVIEW

**Comment by mnikhil-git** [comment]
@svent  Is it possible for you to share the sample data that you have used for benchmarking this and may be the hardware specs, perhaps any scripts to benchmark this? I would like to benchmark against the backdrop of current change.

**Comment by LarryBattle** [comment]
Could you provide a benchmark?

**Comment by mnikhil-git** [comment]
I will need help from @svent for this

**Comment by svent** [comment]
Sorry for the late reply on this PR - I finally did some benchmarks on this.

_Searching through 800 small .gz files (800 files, 200 MB uncompressed):_
- original: 0m0.322s
- with PR: 0m0.573s

_Searching one big file (700 MB uncompressed):_
- original: 0m12.416s
- with PR: 0m14.951s

So the PR acutally makes sift slower. This is not because that library is bad (I guess one can find examples where the performance is slightly better) - one reason is that sift is already designed for an optimal balance of CPU and IO load, and especially searching files in parallel cannot benefit from this as sift uses all CPU cores in that case anyway (and using pgzip just adds additional complexity).
sift is just not a good use case for that parallel gzip implementation.

**Pull request closed without merging**
